import Head from 'next/head'

import styled from 'styled-components'
import Link from "next/link";

const MainContainer = styled.div`
  color: #000000;
  display: flex;
  flex-direction: column;
  height: auto;
  width: 100vw;
  background: #F3F8FE;
  
  justify-content: center;
  align-items: center;
  
  padding: 8rem 3rem;
`

const ContentText = styled.div`
  color: #000000;
  font-size: 1.5rem;
  text-align: center;
  
  padding: 2rem 0 1rem 0;
`;

const StartButton = styled.button`
  color: #000000;
  font-size: 1.5rem;
  background: #F3F8FE;
  padding: 0.75rem;
  margin-top: 3rem;
  border: 4px solid #000;
  border-radius: 3rem;
  
  &:hover {
    background: #6aaaab;
  }
`

export default function About() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <MainContainer>
        <h1>Welcome</h1>
        <ContentText>This survey aims to understand and study the effectiveness of different forms of visualisations on consumers, and should take no more than 10 minutes to complete.</ContentText>
        <ContentText><b>This survey requires a mobile phone or tablet with Instagram installed on it. Computers cannot be used.</b></ContentText>
        <ContentText style={{fontSize:"1.5rem"}}>* Your answers are completely anonymous and will solely be used for research purposes.</ContentText>
        
        <Link href={`/survey-1`} style={{ textDecoration: "none" }}>
          <StartButton>Start Survey</StartButton>
        </Link>
        
      </MainContainer>
    </>
  )
}
